### ISSUE TITLE
Crashed while playing song on Android 12

### ISSUE THREAD

**Issue by codeGV** [YajanaRao/Serenity#135]
I think it's issue occur in react-track-player.
E/ReactTrackPlayer: onCreate: java.lang.IllegalArgumentException: com.codegv.kukimusic: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by YajanaRao** [comment]
@codeGV Where is this happening ?.

**Comment by codeGV** [comment]
@YajanaRao This issue happen when play a song using `dispatch(Player.playSong(track));`

This happen only on Targeting S+ (version 31 and above.

**Comment by YajanaRao** [comment]
@codeGV Can you share the repro steps for this ? I don't see this happening on myside
