### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/Serenity#27]
Adding unit tests for all the components of React Native application using Jest.

**Comment by tamirisapbonicenha** [comment]
break this issue into several smaller issues and I'll get some ;)

**Comment by YajanaRao** [comment]
@tamirisapbonicenha I have few tests failing, If you can fix some that would be helpful.

**Comment by tamirisapbonicenha** [comment]
@YajanaRao assign to me, I'll help you

**Comment by YajanaRao** [comment]
@tamirisapbonicenha one of the reason for the test to fail is https://github.com/callstack/react-native-paper/issues/1410. i e because of react native paper. We may need to wait for new version of react native paper.

**Comment by YajanaRao** [comment]
@tamirisapbonicenha can you update the react native paper to 3.1.1 and check the update fixes the issue

**Comment by YajanaRao** [comment]
Issue fixed with latest update
