### ISSUE TITLE
Quote text goes outisde the Quote container

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/Serenity#30]
<img src="https://user-images.githubusercontent.com/38914337/66220336-7a4b4600-e6ea-11e9-810b-6bd7811301ad.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="250" height="450" />
Quote container text is going outside of the container

**Comment by Selich** [comment]
I could fix that.

**Comment by YajanaRao** [comment]
If you have any questions, feel free to ask me here.

**Comment by jascaniojah** [comment]
Hi, is this solved?

**Comment by YajanaRao** [comment]
@jascaniojah not yet.

**Comment by YajanaRao** [comment]
@Selich and @jascaniojah I got a walk around for this issue as of now. If you have a better solution please feel free to create a PR.
