### ISSUE TITLE
Change react-navigation-tabs color to react native paper theme color

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/Serenity#38]
Need to change react-navigation-tabs color from it's default to react native paper theme color.

**Comment by hendaoui** [comment]
Assign it to me

**Comment by YajanaRao** [comment]
@hendaoui any updates ?

**Comment by YajanaRao** [comment]
Need to create a custom [tabBarComponent](https://github.com/react-navigation/tabs/issues/204)

**Comment by YajanaRao** [comment]
Fixed with react navigation 5
