### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/Serenity#40]
Need to fix the tests which are failing in the update branch.

**Comment by talieScript** [comment]
I can do it, do you just want me to change the tests?

**Comment by YajanaRao** [comment]
@talieScript yes, need to update tests

**Comment by YajanaRao** [comment]
I have updated the code base. Please checkout the latest version before updating any tests.

**Comment by talieScript** [comment]
cool, on it now

**Comment by talieScript** [comment]
check out https://github.com/YajanaRao/Serenity/pull/47

**Comment by YajanaRao** [comment]
@talieScript Thank you for contributing .
