### ISSUE TITLE
Contain image inside the dialog

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/Serenity#51]
Need to change the size of the image so that it looks good with all screen sizes.
![WhatsApp Image 2019-10-21 at 2 21 36 PM](https://user-images.githubusercontent.com/38914337/67191143-c26aa800-f40e-11e9-8929-300cad468c8e.jpeg)

**Comment by patesson** [comment]
What about using Flex to align the items? Would you want the items to change in size to fill available space or use white-space for that?

**Comment by KarlaChen** [comment]
Hi, @YajanaRao . Can I fix it?

**Comment by YajanaRao** [comment]
Sure

**Comment by YajanaRao** [comment]
@KarlaChen I found a walk around for this issue. If you find a better solution please feel free to create a PR :).
