### ISSUE TITLE
How to add song to the app?

### ISSUE THREAD

**Issue by justinushermawan** [YajanaRao/Serenity#68]
Hi, when I installed the app, my home screen is empty, there is no song in there. How to import some?

**Comment by YajanaRao** [comment]
It plays offline songs. If you have downloaded songs to the device, it must be listed. Let me know if you can't see the downloaded songs.

**Comment by justinushermawan** [comment]
Ohh I see, I'm currently have a plan to enhance this to be able to play streaming song from my API. So, the song will be played from a URI resource, and the playlist too. Is it possible?

**Comment by YajanaRao** [comment]
Yes, possible.

**Comment by justinushermawan** [comment]
is it better to always stream the song every time we play it or download it first to offline database for each playlist?

**Comment by YajanaRao** [comment]
Streaming songs online is the general way of doing

**Comment by justinushermawan** [comment]
Thank you for your input. I'll try it.
