### ISSUE TITLE
The connectivity between the react-track-player and the project is having issues.

### ISSUE THREAD

**Issue by asifmhdashik** [YajanaRao/Serenity#93]
the build is working fine but react-track-player is not working in the build of the app.And when the player and songs are tried to be accessed ,the app just crashes.There is some error with react-track-player's connectivity to the project.Downloads and all are just working fine.Expect a QUICK fIX .Thank you

Uploading screen recorded Video.mp4…

**Comment by asifmhdashik** [comment]
[](url)

https://user-images.githubusercontent.com/76432849/116389855-109a0c00-a83b-11eb-80ef-327aa93e0dc0.mp4

**Comment by asifmhdashik** [comment]
https://user-images.githubusercontent.com/76432849/116389979-38896f80-a83b-11eb-9212-8031cc52b912.mp4

**Comment by asifmhdashik** [comment]
https://user-images.githubusercontent.com/76432849/116390963-37a50d80-a83c-11eb-9fe7-ebcdda342b9b.mp4

**Comment by YajanaRao** [comment]
Are you trying to build the application on your system? What device are you running the app on?

**Comment by YajanaRao** [comment]
Are you trying to build the application on your system? What device are you running the app on?

**Comment by asifmhdashik** [comment]
yes I am trying to build the application on the system and the app is running in an android device.I tried both master and monorepo branches.Can you please tell what is causing this.
![Screenshot 2021-04-28 at 9 35 04 PM](https://user-images.githubusercontent.com/76432849/116436193-c7ad7c00-a869-11eb-9652-047accc66752.png)
![Screenshot 2021-04-28 at 9 35 24 PM](https://user-images.githubusercontent.com/76432849/116436232-d1cf7a80-a869-11eb-969d-ae96eff28972.png)

**Comment by YajanaRao** [comment]
Pull the latest version of all branches.

**Comment by asifmhdashik** [comment]
Will that solve these problems

**Comment by YajanaRao** [comment]
It must solve the issue. Let me know if it does not

**Comment by asifmhdashik** [comment]
This build script  ./gradlew assembleRelease  --no-daemon gave this error and build failed due line 135 in build.gradle of android 



![Screenshot 2021-04-28 at 10 44 50 PM](https://user-images.githubusercontent.com/76432849/116445379-773b1c00-a873-11eb-9e34-65b730aafb7b.png)
![Screenshot 2021-04-28 at 10 45 08 PM](https://user-images.githubusercontent.com/76432849/116445419-7c986680-a873-11eb-8682-8e2e7f1afa0b.png)

**Comment by asifmhdashik** [comment]
![Screenshot 2021-04-28 at 10 52 09 PM](https://user-images.githubusercontent.com/76432849/116446286-6b038e80-a874-11eb-99a2-f92b399d0376.png)

**Comment by YajanaRao** [comment]
Can you share the full error log ?.

**Comment by asifmhdashik** [comment]
Creating an .env file didn't solve the problem.
![Screenshot 2021-04-28 at 11 27 30 PM](https://user-images.githubusercontent.com/76432849/116450817-62fa1d80-a879-11eb-99ec-305ffb02fef6.png)

**Comment by YajanaRao** [comment]
Try building after adding the `VERSION_CODE=1` into .env file

**Comment by asifmhdashik** [comment]
The build execution has started . Will inform you the status of the player.

**Comment by asifmhdashik** [comment]
The problem is not solved same problem as the beginning one

https://user-images.githubusercontent.com/76432849/116456595-12d28980-a880-11eb-9b8d-7e917825bdf4.mp4

**Comment by asifmhdashik** [comment]
There are so many errors shown in the src file's components .Can you please tell why.
![Screenshot 2021-04-29 at 1 05 59 PM](https://user-images.githubusercontent.com/76432849/116517150-2adff280-a8ec-11eb-9a37-73f7b01d17a9.png)
![Screenshot 2021-04-29 at 1 06 58 PM](https://user-images.githubusercontent.com/76432849/116517154-2d424c80-a8ec-11eb-8601-b2ebeaedd9f4.png)

**Comment by asifmhdashik** [comment]
Is these errors happening because of some configurations of my system?
Please help am not being able run any native apps without these kind errors. I even tried forking this repository. 😔

**Comment by YajanaRao** [comment]
Hi,
The react track player has been updated. Please make sure you have the latest of react track player. Please do ignore typescript issues.

**Comment by asifmhdashik** [comment]
@YajanaRao Yes it did solve the issue.
