### ISSUE TITLE
Packages are not synchronised

### ISSUE THREAD

**Issue by NeutralDevop** [YajanaRao/Serenity#94]
The packages are downloading but giving error regarding the absence of multiple version of same dependancies. React version being 17.0.1 and some other packages versions are conflicting and this is results in the form of some errors in the app. An updated package. Json file with appropriate versions might solve this. Thank you

**Comment by YajanaRao** [comment]
Are you installing the dependencies using yarn?

**Comment by NeutralDevop** [comment]
Yes

**Comment by YajanaRao** [comment]
Use yarn only. Using npm might have duplicated the packages. Try fresh install once or you can delete the duplicated packages. I will spent time on easing the work flow in near future.

**Comment by NeutralDevop** [comment]
I did a fresh yarn install and got this as the installation log. 
![Screenshot_20210510_225724](https://user-images.githubusercontent.com/83843970/117700158-451aaa00-b1e3-11eb-95ae-5b3713aae740.jpg)

**Comment by YajanaRao** [comment]
Do you still see duplicate packages issue ?

**Comment by YajanaRao** [comment]
I have added Lerna for managing JavaScript projects with multiple packages. Please checkout `feat/lerna` #98 and let me know this solves the issue.

**Comment by NeutralDevop** [comment]
Still facing some errors are coming up. Am using Mac OS ,is it creating these issues.This is the launch.tsx file.And there so many errors like this listed in other files too.
![Screenshot 2021-05-17 at 3 53 44 PM](https://user-images.githubusercontent.com/83843970/118473881-142cfe80-b728-11eb-894d-7099ac66fcd5.png)

**Comment by YajanaRao** [comment]
This typescript warnings won't be an issue. Try installing the app and let me know. I will work on fixing these warnings soon
